package cinema;



import cinema.formCB;
import static cinema.allData.userID;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author jerbi
 */
public class formTicket extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement pst = null;
    public final String movieID;
    boolean reduction = false;
    
    int userID;

    /**
     * Creates new form FormTicket
     */
    public formTicket(String movieID, int userID) {
        initComponents();
        this.movieID = movieID;
        this.userID = userID;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        nbr_ticket = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Please reserve your tickets");

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Number of Tickets :");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Student reduction:");

        jButton1.setBackground(new java.awt.Color(102, 255, 0));
        jButton1.setText("BUY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        nbr_ticket.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        nbr_ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbr_ticketActionPerformed(evt);
            }
        });
        nbr_ticket.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nbr_ticketKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nbr_ticketKeyTyped(evt);
            }
        });

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbr_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nbr_ticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButton1))
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String query = "INSERT INTO `payement`( `nbr_ticket`,   `id_film`, `id_user`, `reduction`) VALUES (?,?,?,?)";
            con = DriverManager.getConnection("jdbc:mysql://localhost:3308/billet_cin?zeroDateTimeBehavior=CONVERT_TO_NULL","root","");
            pst=  con.prepareStatement(query);
            int nbr = Integer.parseInt(this.nbr_ticket.getText());
            int movieIDInt = Integer.parseInt(this.movieID);
            
            pst.setInt(1,  nbr  );
            
             pst.setInt(2,  movieIDInt  );
             
             
             pst.setInt(3,  this.userID  );
             
             pst.setInt(4,  this.reduction == false ? 0 : 20  );
             
             
            
            
            
            pst.execute();
            
  JOptionPane.showMessageDialog(null, "Your information has been saved, you will be transferred to the payment page");
        formCB confirm  = new formCB(movieID,this.userID);
        confirm.setVisible(true);
        setVisible(false);
            
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null,ex);
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nbr_ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbr_ticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbr_ticketActionPerformed

    private void nbr_ticketKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nbr_ticketKeyTyped
       char c=evt.getKeyChar();
       
       if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
           evt.consume();
       }
       
    }//GEN-LAST:event_nbr_ticketKeyTyped

    private void nbr_ticketKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nbr_ticketKeyPressed
        // TODO add your handling code here:
        //action when key is pressed
        String numberTickets=nbr_ticket.getText();
        int length=numberTickets.length();
        char c=evt.getKeyChar();
        if(evt.getKeyChar()>='0'&&evt.getKeyChar()<='9'){
            if(length<1){
                nbr_ticket.setEditable(true);
            }else{
                nbr_ticket.setEditable(false);
            }
        }else{
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACK_SPACE||evt.getExtendedKeyCode()==KeyEvent.VK_DELETE){
                 nbr_ticket.setEditable(true);
            }else{
                nbr_ticket.setEditable(false);
            }
            
        }
    }//GEN-LAST:event_nbr_ticketKeyPressed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
        this.reduction = ! this.reduction;
    }//GEN-LAST:event_jRadioButton1ActionPerformed

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField nbr_ticket;
    // End of variables declaration//GEN-END:variables
}
